config/routes.rb
Rails.application.routes.draw do
  root 'admin#index'
  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders do
    get :autocomplete_customer_shop_name, :on => :collection
    match :delete_order_product, :on => :member, :via => :post
  end
  resources :products
  resources :customers do
    get :autocomplete_city_area, :on => :collection
  end
  resources :vendors do
    get :send_orders, :on => :collection
  end
  resources :cities
end

app/models/customer.rb
class Customer < ApplicationRecord
	 before_save 						:update_address_line
	 has_many								:orders
	 validates						  :contact_number_1, uniqueness: true

	def address_line
		address = ''
		address += address_line_1 if address_line_1.present?
		address += ', ' + address_line_2 if address_line_2.present?
		address += ', ' + address_line_3 if address_line_3.present?
		return address
	end

	def city_and_district
		area + ', ' + city + ', ' + taluk + ', ' + district + ' - ' + pin_code
	end

	def full_address
		address_line + ', ' + area + ', ' + city +  ' - ' + pin_code + ', ' + taluk + ', ' + district + ', ' + state
	end

	def mobile_number
		mobile_number = ''
		mobile_number += contact_number_1 if contact_number_1.present?
		mobile_number += ' | ' + contact_number_2 if contact_number_2.present?
		return mobile_number
	end

	def shop_name_with_city
		"#{self.shop_name}, #{self.city}"
	end

	private

		def update_address_line	
			self.address_line_1.slice! "Tailors" if self.is_tailors_changed? && self.shop_name.include?("Tailors")
			self.address_line_1.slice! "Upstair : " if self.is_upstair_changed? && self.address_line_1.include?("Upstair : ")
			self.address_line_2.slice! "Opposite : " if self.is_opposite_or_near_changed? && self.address_line_2.include?("Opposite : ")
			self.address_line_2.slice! "Near : " if self.is_opposite_or_near_changed? && self.address_line_2.include?("Near : ")
			self.address_line_3.slice! "Back Side" if self.is_back_side_of_changed? && self.address_line_3.include?("Back Side")

			self.shop_name = "#{self.shop_name} #{self.is_tailors}" if self.is_tailors_changed?
			self.address_line_1 = "#{self.is_upstair} #{self.address_line_1}" if self.is_upstair_changed?
			self.address_line_2 = "#{self.is_opposite_or_near} #{self.address_line_2}" if self.is_opposite_or_near_changed?
			self.address_line_3 = "#{self.address_line_3} #{self.is_back_side_of}" if self.is_back_side_of_changed?
		end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  autocomplete  :city, :area, :display_value => :area_with_city, :extra_data => [:area, :city, :taluk, :district, :state, :pin_code]

   def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
    render  :action => 'new'
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit( :name, :shop_name, :address_line_1, :address_line_2, :address_line_3, :area, :city, :taluk, :district, :state, :pin_code,
                                        :contact_number_1, :contact_number_2, :email, :website, :is_tailors, :is_upstair, :is_opposite_or_near, :is_back_side_of)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer,  :html => {:class => 'form-inline'}) do |f| %>
  <% if @customer.errors.any? %>
    <div class="alert alert-success" role="alert">
      <h2 class="alert-heading"><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr class="row">
      <td>Name</td>
      <td><%= f.text_field :name, :placeholder => "Name", :required => true %></td>
      <td style="width:100px;"></td>
      <td style="text-align:right;">Shop Name&nbsp;&nbsp;</td>
      <td style="width:300px;"><%= f.text_field :shop_name, :placeholder => "Shop Name", :required => true %>&nbsp;&nbsp;<%= f.check_box :is_tailors, {:checked => true}, 'Tailors', '' %>&nbsp;&nbsp;&nbsp;Tailors</td>
    </tr>
    <tr class="row">
      <td>Mobile Number</td>
      <td colspan="2"><%= f.text_field :contact_number_1, :placeholder => "Primary Number", :required => true, :minlength=>"10", :pattern => '[0-9]{10}\b', :style => "width:100%;" %></td>
      <td>&nbsp;Alternate Number&nbsp;&nbsp;</td>
      <td><%= f.text_field :contact_number_2 %></td>
    </tr>
    <tr class="row">
      <td>Complex/Building Name</td>
      <td colspan="4">&nbsp;&nbsp;&nbsp;<%= f.check_box :is_upstair, {}, 'Upstair :', '' %>&nbsp;&nbsp;Upstair&nbsp;&nbsp;&nbsp;&nbsp;<%= f.text_field :address_line_1, :placeholder => "Complex/Building Name", :style => "width:72.5%;" %></td>
    </tr>
    <tr class="row">
      <td>Street Name</td>
      <td colspan="4"><%= f.radio_button :is_opposite_or_near, 'Opposite :', :style => "width:4%;" %>&nbsp;Opposite&nbsp;&nbsp;<%= f.radio_button :is_opposite_or_near, 'Near :', :style => "width:4%;" %>&nbsp;Near&nbsp;&nbsp;<%= f.radio_button :is_opposite_or_near, '', :style => "width:4%;" %><%= f.text_field :address_line_2, :placeholder => "Street Name", :style => "width:57.5%;" %></td>
    </tr>
    <tr class="row">
      <td>Land Mark</td>
      <td><%= f.text_field :address_line_3, :placeholder => "Land Mark" %></td>
      <td>&nbsp;&nbsp;<%= f.check_box :is_back_side_of, {}, 'Back Side', '' %>&nbsp;&nbsp;BackSide</td>
      <td style="text-align:right;">&nbsp;Area&nbsp;&nbsp;</td>
      <td><%= f.autocomplete_field :area, autocomplete_city_area_customers_path, update_elements:{area: '#customer_area', city: '#customer_city', taluk: '#customer_taluk', district: '#customer_district', state: '#customer_state', pin_code: '#customer_pin_code'}, :required => true %></td>
    </tr>
    <tr class="row">
      <td>City</td>
      <td colspan="2"><%= f.text_field :city, :style => "width:100%;" %></td>
      <td style="text-align:right;">&nbsp;Taluk&nbsp;&nbsp;</td>
      <td><%= f.text_field :taluk %></td>
    </tr>
    <tr class="row">
      <td>District</td>
      <td colspan="2"><%= f.text_field :district, :style => "width:100%;" %></td>
      <td style="text-align:right;">&nbsp;State&nbsp;&nbsp;</td>
      <td><%= f.text_field :state %></td>
    </tr>
    <tr class="row">
      <td colspan="3"></td>
      <td style="text-align:right;">Pin Code</td>
      <td><%= f.text_field :pin_code, :placeholder => "Pin Code", :required => true, :minlength=>"6", :pattern => '[0-9]{6}\b' %></td>
    </tr>
    <tr class="row">
      <td>Email</td>
      <td colspan="2"><%= f.email_field :email, :placeholder => "E-Mail", :style => "width:100%;" %></td>
      <td style="text-align:right;">&nbsp;Web Site&nbsp;&nbsp;</td>
      <td><%= f.text_field :website, :placeholder => "Web Site" %></td>
    </tr>
  </table>
  <%= f.submit :class => "btn btn-success" %>
<% end %>

<script src="/javascripts/application.js"></script>

app/views/customers/edit.html.erb
<h1>Update Customer&nbsp;&nbsp;<%= link_to image_tag('back.png', :alt => 'back', :title => 'Go back'), 'javascript:window.history.back();' %></h1>

<%= render 'form', user: @customer %>

app/views/customers/index.html.erb
<h1>Customers</h1>

<%= link_to 'New Customer', new_customer_path, :class =>"btn btn-primary pull-xs-right" %><br/><br/>
<p id="notice"><%= notice %></p>
<table class="table table-sm table-inverse">
  <thead>
    <tr>
      <th>Id</th>
      <th>Shop Name</th>
      <th>Name</th>
      <th>Address</th>
      <th>City & District</th>
      <th>Contact Number</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.id, customer %></td>
        <td><%= customer.shop_name %></td>
        <td><%= customer.name %></td>
        <td><%= customer.address_line %></td>
        <td><%= customer.city_and_district %></td>
        <td><%= customer.contact_number_1 %></td>
        <td><%= link_to image_tag('edit.png', :alt => 'Edit', :title => 'Edit'), edit_customer_path(customer) %>&nbsp;&nbsp;<%= link_to image_tag('cross.png', :alt => 'Delete', :title => 'Delete'), customer_path(customer), method: :delete, data: { confirm: 'Are you sure you want to delete this Customer ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<h1>New Customer&nbsp;&nbsp;<%= link_to image_tag('back.png', :alt => 'back', :title => 'Go back'), 'javascript:window.history.back();' %></h1>

<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @customer.shop_name %>&nbsp;&nbsp;<%= link_to image_tag('back.png', :alt => 'back', :title => 'Go back'), 'javascript:window.history.back();' %></h1>
<p class="pull-xs-right"><%= link_to image_tag('create.png', :alt => 'Create Order', :title => 'Create Order'), new_order_path(:customer_id => @customer) %></p>
<table>
    <tr>
      <td><b>Name</b></td>
      <td style="width:50px;">:-</td>
      <td><%= @customer.name %></td>
    </tr>
    <tr>
      <td><b>Mobile Number</b></td>
      <td>:-</td>
      <td><%= @customer.mobile_number %></td>
    </tr>
    <tr>
      <td><b>Address</b></td>
      <td>:-</td>
      <td><%= @customer.full_address %></td>
    </tr>
    <% if  @customer.email.present? %>
      <tr>
        <td><b>E-Mail</b></td>
        <td>:-</td>
        <td><%= @customer.email %></td>
      </tr>
    <% end %>
    <% if  @customer.website.present? %>
      <tr>
        <td><b>WebSite</b></td>
        <td>:-</td>
        <td><%= @customer.website %></td>
      </tr>
    <% end %>
  </table>
  <br/>
  <table class="table table-sm" style="width:250px;">
    <tr><td><b>Total Amount</b></td><td style="float:right; color:red;"><%= @customer.orders.map(&:total_charges).sum %></td></tr>
    <tr><td><b>Advanced & Payed</b></td><td style="float:right; color:green;"><%= "500" %></td></tr>
    <tr><td><b>Remaining</b></td><td style="float:right; color:blue;"><%= @customer.orders.map(&:total_charges).sum - 500 %></td></tr>
  </table>
  <br/>
  <h3>Orders</h3>
  <table class="table table-sm table-striped">
    <thead>
      <tr>
        <th>Number</th>
        <th>Product</th>
        <th>Units</th>
        <th>Booking Date</th>
        <th>Expected Delivery Date</th>
        <th>Price</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @customer.orders.each do |order| %>
        <tr>
          <td><%= link_to order.display_number, order %></td>
          <td style="width:300px;""><%= order.order_products.map(&:product_name).map(&:inspect).join(', ') %></td> 
          <td><%= order.total_units %></td>
          <td><%= order.booking_at.to_date %></td>
          <td><%= order.order_products.map(&:expected_delivery_date).min.to_date %></td>
          <td>&#8377;<%= order.total_charges %></td>
          <td><%= link_to image_tag('edit.png', :alt => 'Edit', :title => 'Edit'), edit_order_path(order) %>&nbsp;&nbsp;<%= link_to image_tag('cross.png', :alt => 'Delete', :title => 'Delete'), order_path(order), method: :delete, data: { confirm: 'Are you sure you want to delete this Order ?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>