config/routes.rb
Rails.application.routes.draw do
  root 'admin#index'
  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders do
    get :autocomplete_customer_shop_name, :on => :collection
    match :delete_order_product, :on => :member, :via => :post
  end
  resources :products
  resources :customers do
    get :autocomplete_city_area, :on => :collection
  end
  resources :vendors do
    get :send_orders, :on => :collection
  end
  resources :cities
end

app/models/vendor.rb
class Vendor < ApplicationRecord

	 has_many								:order_products
	 validates						  :contact_number_1, uniqueness: true

	def address_line
		address = ''
		address += address_line_1 if address_line_1.present?
		address += ', ' + address_line_2 if address_line_2.present?
		address += ', ' + address_line_3 if address_line_3.present?
		return address
	end

	def city_and_district
		city + ', ' + taluk + ', ' + district + ' - ' + pin_code
	end

	def full_address
		address_line + ', ' + city + ', ' + taluk + ', ' + district + ', ' + state + ' - ' + pin_code
	end

	def mobile_number
		mobile_number = ''
		mobile_number += contact_number_1 if contact_number_1.present?
		mobile_number += ' | ' + contact_number_2 if contact_number_2.present?
		return mobile_number
	end
	
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
	before_action :set_vendor, only: [:show, :edit, :update, :destroy, :send_orders]

   def index
    @vendors = Vendor.all
  end

  def show
  end

  def new
    @vendor = Vendor.new
    render  :action => 'new'
  end

  def edit
  end

  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'vendor was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def send_orders
    @order_products = @vendor.order_products
    respond_to do |format|
      format.html
      format.pdf do
        #render pdf: "sample"
        pdf1 = WickedPdf.new.pdf_from_string(render_to_string('vendors/send_orders.pdf.erb', layout: 'layouts/pdf.html.erb'))
        send_data pdf1, :filename => "#{@vendor.company_name}_#{Date.today}.pdf", :type => "application/pdf", :disposition => "attachment"
      end
    end
  end

  private

    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit( :name, :company_name, :address_line_1, :address_line_2, :address_line_3, :city, :taluk, :district, :state, :pin_code,
                                      :contact_number_1, :contact_number_2, :email, :website)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>
      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <table>
    <tr>
      <td><b>Company Name</b></td>
      <td colspan="2"><%= f.text_field :company_name, :placeholder => "Company Name", :required => true %></td>
      <td style="text-align:right;"><b>Name</b>&nbsp;&nbsp;</td>
      <td style="width:300px;"><%= f.text_field :name, :placeholder => "Name" %></td>
    </tr>
    <tr>
      <td><b>Mobile Number</b></td>
      <td><%= f.text_field :contact_number_1, :placeholder => "Primary Number", :required => true, :minlength=>"10", :pattern => '[0-9]{10}\b' %></td>
      <td style="width:100px;"></td>
      <td>&nbsp;<b>Alternate Number</b>&nbsp;&nbsp;</td>
      <td><%= f.text_field :contact_number_2 %></td>
    </tr>
    <tr>
      <td><b>Complex/Building Name</b></td>
      <td colspan="4"><%= f.text_field :address_line_1, :placeholder => "Complex/Building Name"%></td>
    </tr>
    <tr>
      <td><b>Street Name</b></td>
      <td colspan="4"><%= f.text_field :address_line_2, :placeholder => "Street Name" %></td>
    </tr>
    <tr>
      <td><b>Land Mark</b></td>
      <td colspan="2"><%= f.text_field :address_line_3, :placeholder => "Land Mark" %></td>
      <td style="text-align:right;">&nbsp;<b>Pin Code</b>&nbsp;&nbsp;</td>
      <td><%= f.text_field :pin_code, :placeholder => "Pin Code", :required => true, :minlength=>"6", :pattern => '[0-9]{6}\b' %></td>
    </tr>
    <tr>
      <td><b>City</b></td>
      <td colspan="2"><%= f.text_field :city %></td>
      <td style="text-align:right;">&nbsp;<b>Taluk</b>&nbsp;&nbsp;</td>
      <td><%= f.text_field :taluk %></td>
    </tr>
    <tr>
      <td><b>District</b></td>
      <td colspan="2"><%= f.text_field :district %></td>
      <td style="text-align:right;">&nbsp;<b>State</b>&nbsp;&nbsp;</td>
      <td><%= f.text_field :state %></td>
    </tr>
    <tr>
      <td><b>Email</b></td>
      <td colspan="2"><%= f.email_field :email, :placeholder => "E-Mail" %></td>
      <td style="text-align:right;">&nbsp;<b>Web Site</b>&nbsp;&nbsp;</td>
      <td><%= f.text_field :website, :placeholder => "Web Site" %></td>
    </tr>
  </table>
  </div>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/vendors/edit.html.erb
<h1>Update Vendor&nbsp;&nbsp;<%= link_to image_tag('back.png', :alt => 'back', :title => 'Go back'), 'javascript:window.history.back();' %></h1>

<%= render 'form', user: @vendor %>

app/views/vendors/index.html.erb
<h1>Vendors</h1>

<%= link_to 'New Vendor', new_vendor_path, :class =>"btn btn-primary pull-xs-right" %><br/><br/>
<p id="notice"><%= notice %></p>
<table class="table table-sm table-inverse">
  <thead>
    <tr>
      <th>Company Name</th>
      <th>Name</th>
      <th>Address</th>
      <th>City & District</th>
      <th>Contact Number</th>
      <th style="width:20%">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= link_to vendor.company_name, vendor %></td>
        <td><%= vendor.name %></td>
        <td><%= vendor.address_line %></td>
        <td><%= vendor.city_and_district %></td>
        <td><%= vendor.contact_number_1 %></td>
        <td><%= link_to image_tag('edit.png', :alt => 'Edit', :title => 'Edit'), edit_vendor_path(vendor) %>&nbsp;&nbsp;<%= link_to image_tag('cross.png', :alt => 'Delete', :title => 'Delete'), vendor_path(vendor.id), method: :delete, data: { confirm: 'Are you sure you want to delete this vendor ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vendors/new.html.erb
<h1>New Vendor&nbsp;&nbsp;<%= link_to image_tag('back.png', :alt => 'back', :title => 'Go back'), 'javascript:window.history.back();' %></h1>

<%= render 'form', customer: @vendor %>

app/views/vendors/send_orders.html.erb
<h1>Send Order</h1>
<p id="notice"><%= notice %></p>
<table class="table table-sm table-striped">
    <thead>
      <tr>
        <th class='noprint'><input type="checkbox" id="select_all"/></th>
        <th>Number</th>
        <th>Product</th>
        <th>Units</th>
        <th>Booking Date</th>
        <th>Expected Delivery Date</th>
      </tr>
    </thead>

    <tbody>
      <% @order_products.each do |op| %>
        <tr>
          <td class='noprint'><input type="checkbox" name="order_products[<%=op.id%>]" class="lr_select"/></td>
          <td><%= op.id %></td>
          <td><%= op.product_name %></td> 
          <td><%= op.units %></td>
          <td><%= op.order.booking_at.to_date %></td>
          <td><%= op.expected_delivery_date.to_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <script type="text/javascript">
    $('#select_all').click(function() {
       if (this.checked) {
           $(':checkbox').each(function() {
               this.checked = true;                        
           });
       } else {
          $(':checkbox').each(function() {
               this.checked = false;                        
           });
       } 
    });
  </script>

app/views/vendors/send_orders.pdf.erb
<h1>Send Order</h1>
<p id="notice"><%= notice %></p>


<table style="width:100%;">
	<% @order_products.each_with_index do |op, i| %>
		<% if i.even? %><tr><% end %>
			<td>
		  <table border="1">
		    <tr>
		      <td style="width:50%;"><center><%= wicked_pdf_image_tag(op.avatar.url(:medium), size: "320x140") %></center></td>
		    </tr>
		    <tr><td style="font-size:25px;"><%= "#{op.product.product_size} (#{op.product.product_colour}) #{op.units}" %></td></tr>
		    <tr><td>Notes : <%= op.notes %></td></tr>
		  </table>
		  </td>
		  <td style="width:2%;"></td>
		<% if i.odd? %></tr><tr style="height:20px;"></tr><% end %>
	<% end %>
</table>

<style type="text/css">
	table, tr, td, th, tbody, thead, tfoot {
    page-break-inside: avoid;
}
</style>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @vendor.company_name %>&nbsp;&nbsp;<%= link_to image_tag('back.png', :alt => 'back', :title => 'Go back'), 'javascript:window.history.back();' %></h1>
<p class="pull-xs-right"><%= link_to image_tag('down.png', :alt => 'Download PDF', :title => 'Download PDF'), send_orders_vendors_path(:id => @vendor, :format => :pdf)%><%= link_to image_tag('message.png', :alt => 'Send Order', :title => 'Send Order'), send_orders_vendors_path(:id => @vendor) %></p>
<table>
    <tr>
      <td><b>Name</b></td>
      <td style="width:50px;">:-</td>
      <td><%= @vendor.name %></td>
    </tr>
    <tr>
      <td><b>Mobile Number</b></td>
      <td>:-</td>
      <td><%= @vendor.mobile_number %></td>
    </tr>
    <tr>
      <td><b>Address</b></td>
      <td>:-</td>
      <td><%= @vendor.full_address %></td>
    </tr>
    <% if  @vendor.email.present? %>
      <tr>
        <td><b>E-Mail</b></td>
        <td>:-</td>
        <td><%= @vendor.email %></td>
      </tr>
    <% end %>
    <% if  @vendor.website.present? %>
      <tr>
        <td><b>WebSite</b></td>
        <td>:-</td>
        <td><%= @vendor.website %></td>
      </tr>
    <% end %>
  </table>
  <br/><br/><br/>
  <h3>Order Products</h3>
  <table class="table table-sm table-striped">
    <thead>
      <tr>
        <th>Number</th>
        <th>Product</th>
        <th>Units</th>
        <th>Booking Date</th>
        <th>Expected Delivery Date</th>
      </tr>
    </thead>

    <tbody>
      <% @vendor.order_products.each do |op| %>
        <tr>
          <td><%= op.id %></td>
          <td><%= op.product_name %></td> 
          <td><%= op.units %></td>
          <td><%= op.order.booking_at.to_date %></td>
          <td><%= op.expected_delivery_date.to_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>