config/routes.rb
Rails.application.routes.draw do
  root 'admin#index'
  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders do
    get :autocomplete_customer_shop_name, :on => :collection
    match :delete_order_product, :on => :member, :via => :post
  end
  resources :products
  resources :customers do
    get :autocomplete_city_area, :on => :collection
  end
  resources :vendors do
    get :send_orders, :on => :collection
  end
  resources :cities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord

	def area_with_city
		"#{area}, #{city}"
	end
end

app/models/customer.rb
class Customer < ApplicationRecord
	 before_save 						:update_address_line
	 has_many								:orders
	 validates						  :contact_number_1, uniqueness: true

	def address_line
		address = ''
		address += address_line_1 if address_line_1.present?
		address += ', ' + address_line_2 if address_line_2.present?
		address += ', ' + address_line_3 if address_line_3.present?
		return address
	end

	def city_and_district
		area + ', ' + city + ', ' + taluk + ', ' + district + ' - ' + pin_code
	end

	def full_address
		address_line + ', ' + area + ', ' + city +  ' - ' + pin_code + ', ' + taluk + ', ' + district + ', ' + state
	end

	def mobile_number
		mobile_number = ''
		mobile_number += contact_number_1 if contact_number_1.present?
		mobile_number += ' | ' + contact_number_2 if contact_number_2.present?
		return mobile_number
	end

	def shop_name_with_city
		"#{self.shop_name}, #{self.city}"
	end

	private

		def update_address_line	
			self.address_line_1.slice! "Tailors" if self.is_tailors_changed? && self.shop_name.include?("Tailors")
			self.address_line_1.slice! "Upstair : " if self.is_upstair_changed? && self.address_line_1.include?("Upstair : ")
			self.address_line_2.slice! "Opposite : " if self.is_opposite_or_near_changed? && self.address_line_2.include?("Opposite : ")
			self.address_line_2.slice! "Near : " if self.is_opposite_or_near_changed? && self.address_line_2.include?("Near : ")
			self.address_line_3.slice! "Back Side" if self.is_back_side_of_changed? && self.address_line_3.include?("Back Side")

			self.shop_name = "#{self.shop_name} #{self.is_tailors}" if self.is_tailors_changed?
			self.address_line_1 = "#{self.is_upstair} #{self.address_line_1}" if self.is_upstair_changed?
			self.address_line_2 = "#{self.is_opposite_or_near} #{self.address_line_2}" if self.is_opposite_or_near_changed?
			self.address_line_3 = "#{self.address_line_3} #{self.is_back_side_of}" if self.is_back_side_of_changed?
		end
end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to 			:customer
	belongs_to 			:vendor
	has_many   			:order_products, 	:dependent  => :destroy
	accepts_nested_attributes_for 	:order_products, :allow_destroy => true

	def display_number
		number || "PH: #{id}"
	end
	
	def customer_name
		customer.shop_name if customer.present?
	end

	def vendor_name
		vendor.company_name
	end

	def status
		"Created"
	end

	def total_units
		order_products.map(&:units).map(&:to_i).sum
	end

	def total_charges
		order_products.map(&:total_customer_charge).sum.to_f
	end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord

  belongs_to        :order
	belongs_to        :vendor
  belongs_to        :product
  belongs_to        :send_order
	has_attached_file :avatar, styles: { medium: "300x300>" }, default_url: "/images/:style/missing.png",
                    :path => "/Sites/shared/images/:class/:attachment/:id_partition/:style/:filename",
                    :url => '/system/:class/:attachment/:id_partition/:style/:filename'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def customer_charges
  	product.customer_unit_price.to_f
  end

  def vendor_charges
    product.vendor_unit_price.to_f
  end
 
  def product_name
  	product.product_name
  end

  def total_customer_charge
    (customer_charges * units).to_f
  end

end

app/models/product.rb
class Product < ApplicationRecord
	has_many  :order_products
end

app/models/send_order.rb
class SendOrder < ApplicationRecord

	 has_many								:order_products
	
end

app/models/user.rb
require 'digest/sha1'
class User < ApplicationRecord
  has_secure_password

  after_validation            :generate_password, :on => :create
  before_update               :encrypt_password

  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  def self.authenticate(login_or_email, password)
    u = where("login = ? OR email = ?", login_or_email, login_or_email).first
    u && u.authenticated?(password) ? u : nil
  end

  # Encrypts some data with the salt.
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end

  # Encrypts the password with the user salt
  def encrypt(password)
    self.class.encrypt(password, salt)
  end

  def authenticated?(password)
    password_digest == encrypt(password)
  end

  def generate_password
  	self.salt = Digest::SHA1.hexdigest("--#{Time.current.to_s}--#{login}--") if new_record?
  	self.password_digest = encrypt(password)
  end

  def encrypt_password
    return if password.blank?
    self.salt = Digest::SHA1.hexdigest("--#{Time.current.to_s}--#{login}--") if new_record?
    self.password_digest = encrypt(password)
  end

  def password_required?
    password_digest.blank? || password.present?
  end

  def customer_list
    Customer.order(:shop_name).all.map{|c| ["#{c.shop_name}, #{c.city}", c.id]}
  end

  def vendor_list
    Vendor.order(:company_name).all.map{|c| ["#{c.company_name}", c.id]}
  end
end

app/models/vendor.rb
class Vendor < ApplicationRecord

	 has_many								:order_products
	 validates						  :contact_number_1, uniqueness: true

	def address_line
		address = ''
		address += address_line_1 if address_line_1.present?
		address += ', ' + address_line_2 if address_line_2.present?
		address += ', ' + address_line_3 if address_line_3.present?
		return address
	end

	def city_and_district
		city + ', ' + taluk + ', ' + district + ' - ' + pin_code
	end

	def full_address
		address_line + ', ' + city + ', ' + taluk + ', ' + district + ', ' + state + ' - ' + pin_code
	end

	def mobile_number
		mobile_number = ''
		mobile_number += contact_number_1 if contact_number_1.present?
		mobile_number += ' | ' + contact_number_2 if contact_number_2.present?
		return mobile_number
	end
	
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def settings
  	render  :action => '_settings'
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		User.find_by_id(session[:user_id])
	end

	def active_class(link_path)
  	current_page?(link_path) ? "active" : ""
 	end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/_topnav.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <%= link_to 'Narmadha', admin_path, :class =>"navbar-brand" %>
  <ul class="nav navbar-nav">
    <li class="nav-item <%= active_class(customers_path) %>">
      <%= link_to 'Customers', customers_path, :class =>"nav-link" %>
    </li>
    <li class="nav-item <%= active_class(orders_path) %>">
      <%= link_to 'Orders', orders_path, :class =>"nav-link" %>
    </li>
    <li class="nav-item <%= active_class(vendors_path) %>">
      <%= link_to 'Vendors', vendors_path, :class =>"nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Delivery', customers_path, :class =>"nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Bills', charges_path, :class =>"nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Reports', customers_path, :class =>"nav-link" %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Setting</a>
      <div class="dropdown-menu">        
        <%= link_to 'Product', products_path, :class =>"dropdown-item" %>
        <%= link_to 'City', cities_path, :class =>"dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to 'User', users_path, :class =>"dropdown-item" %>
      </div>
    </li>
    <li class="nav-item pull-xs-right">
      <%= link_to 'Logout', sessions_destroy_path, :class =>"nav-link" %>
    </li>
  </ul>
  <form class="form-inline pull-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Narmadha</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'rails' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<% if !(params[:controller] == "sessions" && params[:action] == "new") %>
      <link rel="stylesheet" href="/stylesheets/date_picker.css">
      <script src="/javascripts/application.js"></script>
      <%= javascript_include_tag "date_picker" %>
  		<%= render :partial => 'layouts/topnav' %><br/><br/>
      <div class="container">
        <%= yield %>
      </div>
  	<% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
</head>
<body>

  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>